POST https://fcm.googleapis.com/v1/projects/taaza-today/messages:send
Content-Type: application/json
Authorization:key  XPX1HMXfrDG5oeVAmgkZDE5ciQuZT6jywNJlhEZ1YKY

{
  "message": {
    "topic": "test",
    "data": {
      "title": "Deep Link Test",
      "body": "Tap to open link",
      "deeplink": "https://taaza-today.web.app/en/quiks/2025-10-27T05:18:12-07:00"
    }
  }
}

###

# curl -X POST https://taaza-today-e5tjti1p4-mohamed-elnagars-projects-533f78fa.vercel.app/api/send
#  -H "Content-Type: application/json"
#  -d '{"token":"REAL_FCM_TOKEN","title":"Hello","body":"from Vercel"}'
POST https://taaza-today-fcm.vercel.app/api/send
Content-Type: application/json

{
  "to": "test101",
  "notification": {
    "title": "Hello",
    "body": "World",
    "deeplink": "myapp://detail/42"
  }
}

###


