### Retrieve blog metadata by blogId
GET https://www.googleapis.com/blogger/v3/blogs/3213900?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json

### Retrieve blog metadata by URL
GET https://www.googleapis.com/blogger/v3/blogs/byurl?url=http://code.blogger.com/&key=YOUR_API_KEY
Accept: application/json
### Retrieve blog metadata by URL
GET https://www.googleapis.com/blogger/v3/blogs/byurl?url=https://taazatodayenglish.blogspot.com/2025/09/test-20.html/&key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json

### Retrieve list of posts for this blog
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/posts?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json
### Get blog ID by URL
GET https://www.googleapis.com/blogger/v3/blogs/byurl?url=https://sarkarisnapz.blogspot.com/&key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json

### Retrieve list of posts for this blog (using the obtained blog ID)
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/posts?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json
### Retrieve list of posts for this blog (using the obtained blog ID)
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/posts?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json
#retrieve list of pages
### Retrieve list of posts for the english blog (using the obtained blog ID)
GET https://www.googleapis.com/blogger/v3/blogs/2640395952322331775/posts?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json
### Retrieve list of pages for this blog
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/pages?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
Accept: application/json
### Get page ID by URL 4565115267629106377
#4812052307209681714
#7099357402796700169
#9009084679096542491
#3968644153225120990
#847919335082049403
#6247905743648035844
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/pages/4812052307209681714?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
### Retrieve a single post (replace POST_ID with a real post ID)
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/pages/6247905743648035844?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
### Retrieve a single post (replace POST_ID with a real post ID)
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/pages/847919335082049403?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
### Retrieve a single post (replace POST_ID with a real post ID)
GET https://www.googleapis.com/blogger/v3/blogs/190535731829050983/posts
    ?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
    &maxResults=5
    &labels=Tech
    &startDate=2025-09-11T11:07:24-07:00
    &orderBy=updated
    &fields=nextPageToken,items(id,updated,url,title,content,labels)
### getting the vedio from the post content
GET https://video.blogger.com/video-play.mp4?contentId=faeec605ecb48d94
### Retrieve posts from english blog
GET https://www.googleapis.com/blogger/v3/blogs/2640395952322331775/posts
    ?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
    &maxResults=2
    &endDate=2025-09-30T11:07:24-07:00
    &orderBy=updated
    &fields=nextPageToken,items(id,updated,url,title,content,labels)
### Retrieve posts from english blog page2
GET https://www.googleapis.com/blogger/v3/blogs/2640395952322331775/posts
    ?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
    &maxResults=2
    &endDate=2025-09-30T07:23:48-07:00
    &orderBy=updated
    &fields=nextPageToken,items(id,updated,url,title,content,labels)
### Retrieve posts from english blog page3
GET https://www.googleapis.com/blogger/v3/blogs/2640395952322331775/posts
    ?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
    &maxResults=2
    &endDate=2025-09-30T07:21:45-07:00
    &orderBy=updated
    &fields=nextPageToken,items(id,updated,url,title,content,labels)
### Retrieve posts from english blog page4
GET https://www.googleapis.com/blogger/v3/blogs/2640395952322331775/posts
    ?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
    &maxResults=2
    &endDate=2025-09-30T07:18:57-07:00
    &orderBy=updated
    &fields=nextPageToken,items(id,updated,url,title,content,labels)
### Retrieve posts from english blog page5
GET https://www.googleapis.com/blogger/v3/blogs/2640395952322331775/posts
    ?key=AIzaSyDC4e2G_xH_ho3oxKf9Rm-plxJU8GyBfQY
    &maxResults=2
    &endDate=2025-09-30T07:13:55-07:00
    &orderBy=updated
    &fields=nextPageToken,items(id,updated,url,title,content,labels)

# GET https://www.googleapis.com/blogger/v3/blogs/3213900/posts/POST_ID?key=YOUR_API_KEY
# Accept: application/json
